package ask

import (
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

func TestConfigRoundTrip(t *testing.T) {
	path := filepath.Join(t.TempDir(), "nested", "config.toml")
	want := Config{
		Version:             1,
		Driver:              "github",
		Inbox:               "neguse/ask-inbox",
		Responder:           "neguse",
		PollIntervalSeconds: 17,
	}

	if err := saveConfig(path, want); err != nil {
		t.Fatalf("saveConfig() error = %v", err)
	}
	got, err := loadConfig(path)
	if err != nil {
		t.Fatalf("loadConfig() error = %v", err)
	}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("loadConfig() = %+v, want %+v", got, want)
	}
}

func TestConfigPathUsesUserConfigDirectory(t *testing.T) {
	root := t.TempDir()
	t.Setenv("XDG_CONFIG_HOME", root)
	got, err := ConfigPath()
	if err != nil {
		t.Fatalf("ConfigPath() error = %v", err)
	}
	if want := filepath.Join(root, "ask", "config.toml"); got != want {
		t.Fatalf("ConfigPath() = %q, want %q", got, want)
	}
}

func TestLoadConfigMissingSuggestsInit(t *testing.T) {
	t.Setenv("XDG_CONFIG_HOME", t.TempDir())
	_, err := LoadConfig()
	if err == nil || !strings.Contains(err.Error(), "ask init") {
		t.Fatalf("LoadConfig() error = %v, want ask init suggestion", err)
	}
}

func TestParseConfigDefaultAndComments(t *testing.T) {
	cfg, err := parseConfig(strings.NewReader(`
# generated by ask
version = 1
driver = "git#hub" # inline comment
inbox = "neguse/ask-inbox"
responder = "neguse"
`))
	if err != nil {
		t.Fatalf("parseConfig() error = %v", err)
	}
	if cfg.PollIntervalSeconds != 10 {
		t.Errorf("PollIntervalSeconds = %d, want 10", cfg.PollIntervalSeconds)
	}
	if cfg.Driver != "git#hub" {
		t.Errorf("Driver = %q, want %q", cfg.Driver, "git#hub")
	}
}

func TestParseConfigRejectsUnknownKey(t *testing.T) {
	_, err := parseConfig(strings.NewReader("unknown = 1\n"))
	if err == nil || !strings.Contains(err.Error(), "unknown key") {
		t.Fatalf("parseConfig() error = %v, want unknown-key error", err)
	}
}
